### ISSUE TITLE
Modest: Run Tool opens automatically when opening a .modest file

### ISSUE THREAD

**Issue by jjhierck** [raphlcx/modest-vscode#1]
When a .modest file is selected in the Explorer, the Modest: Run Tool opens automatically. This is annoying when opening multiple files or navigating through multiple files. Perhaps an option to disable this behaviour in the Modest Extension Settings would solve this.

**Comment by raphlcx** [comment]
@jjhierck I think you meant to raise this issue to [this Modest extension](https://marketplace.visualstudio.com/items?itemName=ModestExtensionTeam.modestextension) instead.

This repository (modest-vscode) contains a color scheme called "Modest", which is name similarly, but unrelated to The Modest Toolkit.

Closing this issue, but feel free to comment, or re-open if needed.
